name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Java Runtime Environment to run the .jar file
      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre  # Install Java Runtime Environment (JRE)


      # Start the backend by running the .jar file in the background
      - name: Start Backend (Run .jar file)
        run: |
          nohup java -jar demo-backend/demo-0.0.1-SNAPSHOT.jar &  # Run backend in the background

      # Install npm dependencies and run Cypress tests
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15'

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: Cypress_Cucumber_Test
          install-command: npm install
          start: npx cypress run
        continue-on-error: true  # Allow tests to fail without stopping the workflow

      # Wait for Cypress tests to finish
      - name: Wait for Cypress tests to finish
        run: |
          echo "Waiting for Cypress tests to complete..."
          sleep 30  # Adjust the time as needed for tests to complete

      # Stop the backend after the tests are complete
      - name: Stop Backend (optional)
        run: |
          pkill -f 'java -jar demo-backend/demo-0.0.1-SNAPSHOT.jar'  # Kill the backend process

      # Create result HTML page and upload Cypress results
      - name: Upload Cypress results and deploy to GitHub Pages
        run: |
          # Create the directory to store the test results
          mkdir -p gh-pages/cypress-results

          # Copy the Cypress test results (HTML report, videos, screenshots, etc.) to the deployment folder
          cp -r Cypress_Cucumber_Test gh-pages/cypress-results/

          # Create a simple HTML page to display the test result
          RESULT=$(grep -o 'Tests Passed' Cypress_Cucumber_Test/results/*.txt)
          if [[ $RESULT == "Tests Passed" ]]; then
            STATUS="passed"
          else
            STATUS="failed"
          fi

          cat <<EOF > gh-pages/index.html
          <html>
            <head>
              <title>Cypress Test Results</title>
            </head>
            <body>
              <h1>Cypress Test Results</h1>
              <h2>Status: $STATUS</h2>
              <p>Check the results below:</p>
              <ul>
                <li>Test Report: <a href="cypress-results/index.html">View Report</a></li>
              </ul>
            </body>
          </html>
          EOF

          # Deploy to GitHub Pages
          git config --global user.name "ishaninfo"
          git config --global user.email "ishaninfo56@gmail.com"

          git checkout --orphan gh-pages
          git add .
          git commit -m "Deploy Cypress test results"
          git push -f https://github.com/${{ github.repository }}.git gh-pages

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

