name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Java Runtime Environment to run the .jar file
      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre  # Install Java Runtime Environment (JRE)


      # Start the backend by running the .jar file in the background
      - name: Start Backend (Run .jar file)
        run: |
          nohup java -jar demo-backend/demo-0.0.1-SNAPSHOT.jar &  # Run backend in the background

      # Install npm dependencies and run Cypress tests
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15'

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: Cypress_Cucumber_Test
          install-command: npm install
          start: npx cypress run

      # Optionally stop the backend after the tests
      - name: Stop Backend (optional)
        run: |
          pkill -f 'java -jar demo-backend/demo-0.0.1-SNAPSHOT.jar'  # Kill the backend process
